[project]
name = "iasa-bigdata"
version = "0.1.0"
description = "IASA Masters BigData Course Workbook"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "lab-001-hadoop-and-hive",
]

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "jupyterlab>=4.6.4",
]

[tool.uv.sources]
lab-001-hadoop-and-hive = { workspace = true }

[tool.uv.workspace]
members = ["labs/*"]
